readme = """
Total LED count = Horizontal + Vertical LEDs.
For best experience try matching aspect ratio of your display: H/(V+2) ≈ 16/9. E.g. 27/(13+2) = 1.8 ≈ 1.77...
┌──────────────────────────────────────┐
│B-->         Horizontal LEDs          │
├───┬──────────────────────────────┬───┤
│ V │                              │ V │
│ e │                              │ e │
│ r │                              │ r │
│ t │           Display            │ t │
│ i │                              │ i │
│ c │                              │ c │
│ a │                              │ a │
│ l │                              │ l │
├───┴──────────────────────────────┴───┤
│E            Horizontal LEDs       <--│
└──────────────────────────────────────┘
With enabled V-Sync max_fps is ignored.
B is starting point (index 0), clock-wise indexing, until E (last index).
wled_type:
  \"Rgbw\" sends RGBW values to WLED
  \"Rgb\" sends RGB values to WLED
"""
display_index = 0
gpu_index = 0
led_horizontal_count = 27
led_vertical_count = 13
include_cursor = true
max_fps = 60
enable_v_sync = true
wled_type = "Rgbw"
wled_ip = "192.168.1.150"
